# Generated by Django 2.1.5 on 2019-01-25 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('c_id', models.IntegerField(editable=False, primary_key=True, serialize=False, verbose_name='公司id')),
                ('name', models.CharField(max_length=255)),
                ('context', models.TextField(blank=True, null=True, verbose_name='公司介绍')),
                ('addressCountry', models.CharField(max_length=255)),
                ('addressLocality', models.CharField(max_length=255)),
                ('addressRegion', models.CharField(max_length=255)),
                ('numberOfEmployees', models.CharField(max_length=32)),
                ('tags', models.TextField(blank=True, null=True)),
                ('font_page', models.CharField(max_length=255)),
                ('page', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=16)),
                ('working_place', models.CharField(max_length=255)),
                ('class', models.CharField(max_length=255)),
                ('salary', models.CharField(max_length=128)),
                ('link', models.CharField(max_length=255)),
                ('workfor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Company')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.IntegerField(editable=False, primary_key=True, serialize=False, verbose_name='用户ID')),
                ('name', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=64, null=True)),
                ('bio', models.CharField(max_length=255, null=True)),
                ('workfor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Company')),
            ],
        ),
    ]
